import  MyContext  from "@/Helper/Context";
import "./globals.css";

export const metadata = {
  title: "Pratham's App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-4" suppressHydrationWarning>
        <MyContext>
          {children}
        </MyContext>

      </body>
    </html>
  );
}
